### ISSUE TITLE
caddy 2.4.5 broken on Ubuntu 20.04 hosts

### ISSUE THREAD

**Issue by rafaelreis-r** [SlothCroissant/caddy-cloudflaredns#1]
Hey @SlothCroissant 

2.4.5 seems to be broken on Ubuntu Hosts. See here --> https://github.com/caddyserver/caddy/issues/4118
Woke up this morning with this exact issue using your image.

Since your image does not provide tagged versions, I was unable to revert back to 2.4.3. So I edited a Dockerfile real quick to build caddy-cloudflaredns with 2.4.3. Worked perfectly. Sharing this here in case other people experience the same issue. 

Issue is some random Go error like the follwing:

`qtls.ClientHelloInfo doesn't match caddy`

Solution for now:

1. Create a new folder. 
2. `nano Dockerfile`
3. Paste: 
``` 
FROM caddy:2.4.3-builder AS builder

RUN caddy-builder \
    github.com/caddy-dns/cloudflare

FROM caddy:2.4.3

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

4. Build it:
`docker build -t caddyemergency .`

5. Change your container image from `slothcroissant/caddy-cloudflaredns` to `caddyemergency:latest`

Run it, you should be fine. After caddy updates the main image with a fixed version, you may revert back to using `slothcroissant/caddy-cloudflaredns`

**Comment by SlothCroissant** [comment]
Thanks for the heads up, @rafaelreis-r!

I updated the `:latest` tag to lock into 2.4.3 for now. Let me know if this works for you.

In the future, I'll add versioning support into my image.

**Comment by rafaelreis-r** [comment]
> I updated the `:latest` tag to lock into 2.4.3 for now. Let me know if this works for you.

Back in business as expected! Thank you for the quick reply.

**Comment by SlothCroissant** [comment]
@rafaelreis-r Updated to now support basic tagging. Can you try building/running with the `:2.4.3` tag and let me know if this works? I will then revert `:latest` back to the latest ongoing release.

**Comment by rafaelreis-r** [comment]
@SlothCroissant Worked just fine! Thank you for the extra feature! Very handy.
