### ISSUE TITLE
Bump caddy to 2.7.3

### ISSUE THREAD

**Issue by Sprooty** [SlothCroissant/caddy-cloudflaredns#20]
Caddy 2.7.2 is not recommended for use.

**Comment by SlothCroissant** [comment]
Once Caddy (https://hub.docker.com/_/caddy/tags) releases dockerfiles for 2.7.3, i'll pop a build quick. Till then, the dockerfile upstream will fail. 

Will keep an eye out 😄

**Comment by SlothCroissant** [comment]
Resolved via https://github.com/SlothCroissant/caddy-cloudflaredns/commit/f39a79f3b59381452ab93cb001d33cc6f0427935

https://hub.docker.com/layers/slothcroissant/caddy-cloudflaredns/v2.7.3/images/sha256-374e284d5ca7d82750d243d7c2e1aef9891eaeced9d16ffd6dfed1f9e3f8b846?context=explore

**Comment by SlothCroissant** [comment]
Resolved via https://github.com/SlothCroissant/caddy-cloudflaredns/commit/f39a79f3b59381452ab93cb001d33cc6f0427935

https://hub.docker.com/layers/slothcroissant/caddy-cloudflaredns/v2.7.3/images/sha256-374e284d5ca7d82750d243d7c2e1aef9891eaeced9d16ffd6dfed1f9e3f8b846?context=explore
