### ISSUE TITLE
Email field is not needed

### ISSUE THREAD

**Issue by toyo2333** [SlothCroissant/caddy-cloudflaredns#31]
I didn't fill in an email address but still completed the DNS challenge and got the certificate,

i applied 3 domains ，2 succesed from let encrypt，the last one failed with “"error":"HTTP 404 urn:ietf:params:acme:error:malformed - Certificate not found"}”

then caddy tried ZeroSSL ，it succeed but with the msg “missing email address for ZeroSSL; it is strongly recommended to set one for next time”

I'd like to ask,

 1. if I don't set email, what negative impact will it have? 
 
 2. Does this email address necessarily have to be The Cloudflare Email Address?

 3. what should i do now？

**Comment by vkartk** [comment]
Hi @toyo2333 

1. Not setting an email means you won't get expiry notifications, which can lead to certificates expiring without your knowledge. It’s highly recommended to set one.
2. The email doesn't have to be your Cloudflare email; any monitored email will work.
3. I suggest setting an email address to avoid missing important notifications in the future.

**Comment by SlothCroissant** [comment]
Thanks @vkartk ! Sorry I missed this. Appreciate you stepping in to answer. 

Will close this - @toyo2333 let us know if you have other questions.

**Comment by vkartk** [comment]
@toyo2333 You're welcome! It's always a good idea to test your Caddyfile with `caddy validate` before running it.
