### ISSUE TITLE
Will there be a 2.8.4 in docker hub?

### ISSUE THREAD

**Issue by mustaphazorgati** [SlothCroissant/caddy-cloudflaredns#35]
Hey @SlothCroissant!
I saw your [v2.8.4 Release ](https://github.com/SlothCroissant/caddy-cloudflaredns/releases/tag/v2.8.4). Unfortunately I didn't find a 2.8.4 Image on [DockerHub](https://hub.docker.com/r/slothcroissant/caddy-cloudflaredns). 

Will there be a version on DockerHub?

**Comment by SlothCroissant** [comment]
Hey @mustaphazorgati , super sorry for missing this! Not entirely sure what happened on the 2.8.4 release. 

Pushed a new build today manually, this should be pushed once the build completes: https://github.com/SlothCroissant/caddy-cloudflaredns/actions/runs/10865051348
